version: 2
project_name: casbin-forward-auth

builds:
  - id: casbin-forward-auth
    main: ./cmd/casbin-forward-auth/main.go
    binary: casbin-forward-auth
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -a
archives: []
checksum:
  disable: true
changelog:
  use: git
  sort: asc

release:
  github:
    owner: grepplabs
    name: casbin-forward-auth
  draft: false
  prerelease: auto
