name: "Check chart version"

inputs:
  chart_dir:
    description: "Path to the Helm chart directory (where Chart.yaml lives)"
    required: true
  app_version:
    description: "Path to the Helm chart directory (where Chart.yaml lives)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check chart and app versions
      shell: bash
      run: |
        set -euo pipefail

        CHART_DIR="${{ inputs.chart_dir }}"

        CHART_VERSION=$(yq '.version' "${CHART_DIR}/Chart.yaml")
        APP_VERSION=$(yq '.appVersion' "${CHART_DIR}/Chart.yaml")
        VERSION="${{ inputs.app_version }}"

        echo "Chart version: ${CHART_VERSION}"
        echo "App version:   ${APP_VERSION}"
        echo "Git ref name:  ${VERSION}"

        # Rule 1: appVersion must equal v<chart version>
        if [[ "${APP_VERSION}" != "v${CHART_VERSION}" ]]; then
          echo "ERROR: chart appVersion (${APP_VERSION}) must equal v${CHART_VERSION}"
          exit 1
        fi

        # Rule 2: appVersion must equal the git tag / ref_name
        if [[ "${APP_VERSION}" != "${VERSION}" ]]; then
          echo "ERROR: chart appVersion (${APP_VERSION}) must match ${VERSION}"
          exit 1
        fi

        echo "Version checks passed"
